"use client";
import { useEffect, useRef } from "react";
import type { MouseEvent as ReactMouseEvent } from "react";
import type { PossibilityGraph } from "../possibility-engine/model";
import type { ScenarioPersistenceReport } from "../possibility-engine/scenario-persistence";

type Particle={x:number;y:number;vx:number;vy:number;anchor:number;phase:number};
type PersistenceClass="observed_persistent"|"observed_fragile"|"observed_closed"|"indeterminate";
type Center={x:number;y:number;id:string;closed:boolean;selected:boolean;persistence:PersistenceClass};
const hash=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const rand=(seed:number)=>{let x=seed||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967295}};
const motion=(p:PersistenceClass)=>p==="observed_persistent"?{spread:14,speed:.45,jitter:.45}:p==="observed_fragile"?{spread:31,speed:1.8,jitter:1.5}:p==="observed_closed"?{spread:4,speed:.12,jitter:.1}:{spread:21,speed:.9,jitter:.85};
const stroke=(p:PersistenceClass)=>p==="observed_persistent"?"rgba(74,222,128,.72)":p==="observed_fragile"?"rgba(251,146,60,.70)":p==="observed_closed"?"rgba(244,63,94,.35)":"rgba(192,132,252,.62)";
const fill=(p:PersistenceClass,selected:boolean)=>selected?"rgba(217,70,239,.92)":p==="observed_persistent"?"rgba(103,232,249,.55)":p==="observed_fragile"?"rgba(251,146,60,.42)":p==="observed_closed"?"rgba(244,63,94,.14)":"rgba(192,132,252,.38)";

export default function MpeLivingPlasma({graph,persistence,activeId,onSelect}:{graph:PossibilityGraph|null;persistence?:ScenarioPersistenceReport|null;activeId?:string;onSelect?:(id:string)=>void}){
 const ref=useRef<HTMLCanvasElement>(null);const centersRef=useRef<Center[]>([]);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;let frame=0,raf=0;const nodes=graph?.nodes??[],edges=graph?.edges??[],random=rand(hash(graph?.rootStateId??"mpe-idle"));const pMap=new Map((persistence?.possibilities??[]).map(p=>[p.possibilityId,p.classification] as const));const particles:Particle[]=Array.from({length:Math.max(180,nodes.length*62)},(_,i)=>({x:random(),y:random(),vx:0,vy:0,anchor:nodes.length?i%nodes.length:-1,phase:random()*Math.PI*2}));
 const resize=()=>{const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0)};resize();const ro=new ResizeObserver(resize);ro.observe(canvas);
 const draw=()=>{frame++;const w=canvas.clientWidth,h=canvas.clientHeight,t=frame*.007;ctx.clearRect(0,0,w,h);const opens=new Map<string,number>();edges.filter(e=>e.relation==="opens").forEach(e=>opens.set(e.from,(opens.get(e.from)??0)+1));const centers:Center[]=nodes.map((n,i)=>{const incoming=edges.filter(e=>e.to===n.id),depth=incoming.some(e=>e.relation==="depends_on"||e.relation==="opens")?2:1,persistenceClass=pMap.get(n.id)??"indeterminate",a=(i/Math.max(nodes.length,1))*Math.PI*2+(hash(n.id)%100)/100+t*(persistenceClass==="observed_persistent"?.012:persistenceClass==="observed_fragile"?.06:.03),ring=Math.min(w,h)*(.12+depth*.09+(opens.get(n.id)??0)*.008);return{x:w/2+Math.cos(a)*ring,y:h/2+Math.sin(a)*ring,id:n.id,closed:n.lifecycleStage==="rejected"||Boolean(n.closedReason)||persistenceClass==="observed_closed",selected:n.id===activeId,persistence:persistenceClass}});centersRef.current=centers;
 const glow=ctx.createRadialGradient(w/2,h/2,0,w/2,h/2,Math.min(w,h)*.48);glow.addColorStop(0,"rgba(34,211,238,.10)");glow.addColorStop(.48,"rgba(168,85,247,.04)");glow.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
 for(const e of edges){const a=centers.find(c=>c.id===e.from),b=centers.find(c=>c.id===e.to);if(!a||!b)continue;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.setLineDash(e.relation==="depends_on"?[4,7]:e.relation==="closes"?[2,8]:[]);ctx.strokeStyle=e.relation==="opens"?"rgba(34,211,238,.22)":e.relation==="closes"?"rgba(244,63,94,.22)":e.relation==="contradicts"?"rgba(251,146,60,.20)":"rgba(192,132,252,.12)";ctx.lineWidth=e.relation==="opens"?1.2:.8;ctx.stroke();ctx.setLineDash([])}
 particles.forEach((p,i)=>{let tx=w/2,ty=h/2;if(p.anchor>=0&&centers[p.anchor]){const c=centers[p.anchor],m=motion(c.persistence),noise=Math.sin(t*5+p.phase)*m.jitter;tx=c.x+Math.cos(p.phase+t*m.speed)*(m.spread+noise);ty=c.y+Math.sin(p.phase*1.7+t*m.speed)*(m.spread+noise)}const dx=tx-p.x*w,dy=ty-p.y*h;p.vx=(p.vx+dx*.000014)*.972;p.vy=(p.vy+dy*.000014)*.972;p.x+=p.vx;p.y+=p.vy;const x=((p.x%1)+1)%1*w,y=((p.y%1)+1)%1*h,c=p.anchor>=0?centers[p.anchor]:undefined;ctx.beginPath();ctx.arc(x,y,c?.selected?1.8:c?.closed?.65:1.05,0,Math.PI*2);ctx.fillStyle=c?fill(c.persistence,c.selected):"rgba(125,211,252,.25)";ctx.fill()});
 for(const c of centers){ctx.beginPath();ctx.arc(c.x,c.y,c.selected?11:c.closed?4:c.persistence==="observed_fragile"?7:6,0,Math.PI*2);ctx.strokeStyle=c.selected?"rgba(232,121,249,.95)":stroke(c.persistence);ctx.lineWidth=c.selected?1.6:1;ctx.stroke()}
 raf=requestAnimationFrame(draw)};draw();return()=>{cancelAnimationFrame(raf);ro.disconnect()}},[graph,persistence,activeId]);
 const click=(e:ReactMouseEvent<HTMLCanvasElement>)=>{if(!onSelect)return;const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let best:Center|undefined,bestDistance=Infinity;for(const c of centersRef.current){const d=Math.hypot(x-c.x,y-c.y);if(d<bestDistance){bestDistance=d;best=c}}if(best&&bestDistance<65)onSelect(best.id)};
 return <div className="relative min-h-[520px] overflow-hidden rounded-[32px] border border-cyan-300/10 bg-[#01050b]"><canvas ref={ref} onClick={click} className="absolute inset-0 h-full w-full cursor-crosshair"/><div className="pointer-events-none absolute left-5 top-5"><p className="text-[9px] tracking-[.24em] text-cyan-200/45">LIVING POSSIBILITY SPACE</p><p className="mt-2 max-w-sm text-xs leading-5 text-white/35">Estabilidad visual refleja persistencia estructural observada en escenarios explorados. No es probabilidad.</p></div><div className="pointer-events-none absolute bottom-5 left-5 flex flex-wrap gap-2 text-[8px] tracking-[.12em] text-white/30"><span>GREEN STABLE</span><span>·</span><span>ORANGE FRAGILE</span><span>·</span><span>RED CLOSED</span><span>·</span><span>PURPLE UNKNOWN</span><span>·</span><span>NON-PROBABILISTIC</span></div></div>;
}
