"use client";
import { useEffect, useRef, useState } from "react";
import type { MouseEvent as ReactMouseEvent, WheelEvent as ReactWheelEvent } from "react";
import type { PossibilityGraph } from "../possibility-engine/model";
import type { ScenarioPersistenceReport } from "../possibility-engine/scenario-persistence";

type PersistenceClass="observed_persistent"|"observed_fragile"|"observed_closed"|"indeterminate";
type Center={x:number;y:number;id:string;closed:boolean;selected:boolean;persistence:PersistenceClass;birth:number;collapse:number};
const clamp=(v:number,a=0,b=1)=>Math.max(a,Math.min(b,v));
const hash=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const stroke=(p:PersistenceClass)=>p==="observed_persistent"?"rgba(103,232,249,.78)":p==="observed_fragile"?"rgba(251,146,60,.68)":p==="observed_closed"?"rgba(244,63,94,.28)":"rgba(217,70,239,.62)";

export default function MpeLivingPlasma({graph,persistence,activeId,onSelect}:{graph:PossibilityGraph|null;persistence?:ScenarioPersistenceReport|null;activeId?:string;onSelect?:(id:string)=>void}){
 const canvasRef=useRef<HTMLCanvasElement>(null),centersRef=useRef<Center[]>([]),zoomRef=useRef(1),panRef=useRef({x:0,y:0}),dragRef=useRef<{x:number;y:number;px:number;py:number}|null>(null),hoverRef=useRef<string|undefined>(undefined),birthRef=useRef(new Map<string,number>()),collapseRef=useRef(new Map<string,number>()),seenRef=useRef(new Set<string>());
 const [hoveredId,setHoveredId]=useState<string|undefined>(undefined);const hovered=graph?.nodes.find(n=>n.id===hoveredId);
 useEffect(()=>{const now=performance.now();for(const n of graph?.nodes??[]){if(!seenRef.current.has(n.id))birthRef.current.set(n.id,now);const p=persistence?.possibilities.find(x=>x.possibilityId===n.id)?.classification;const closed=n.lifecycleStage==="rejected"||Boolean(n.closedReason)||p==="observed_closed";if(closed&&!collapseRef.current.has(n.id))collapseRef.current.set(n.id,now);seenRef.current.add(n.id)}},[graph,persistence]);
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;let raf=0;const resize=()=>{const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0)};resize();const ro=new ResizeObserver(resize);ro.observe(canvas);
 const draw=()=>{const now=performance.now(),nodes=graph?.nodes??[],edges=graph?.edges??[],w=canvas.clientWidth,h=canvas.clientHeight,z=zoomRef.current,cx=w/2+panRef.current.x,cy=h/2+panRef.current.y;ctx.clearRect(0,0,w,h);const pMap=new Map((persistence?.possibilities??[]).map(p=>[p.possibilityId,p.classification] as const));const targets=nodes.map((n,i)=>{const pc=pMap.get(n.id)??"indeterminate",a=(i/Math.max(nodes.length,1))*Math.PI*2+(hash(n.id)%90)/90,ring=Math.min(w,h)*(.22+(n.parentPossibilityIds.length? .08:0))*z;return{id:n.id,x:cx+Math.cos(a)*ring,y:cy+Math.sin(a)*ring,pc}});const targetMap=new Map(targets.map(t=>[t.id,t]));const centers:Center[]=nodes.map(n=>{const target=targetMap.get(n.id)!;const parentId=n.parentPossibilityIds[0]??edges.find(e=>e.to===n.id&&(e.relation==="opens"||e.relation==="derived_from"))?.from;const parent=parentId?targetMap.get(parentId):undefined;const born=clamp((now-(birthRef.current.get(n.id)??0))/1000);const collapseStart=collapseRef.current.get(n.id);const collapse=collapseStart?clamp((now-collapseStart)/1100):0;const ease=1-Math.pow(1-born,3),sx=parent?.x??cx,sy=parent?.y??cy;return{id:n.id,x:sx+(target.x-sx)*ease,y:sy+(target.y-sy)*ease,closed:collapse>0,selected:n.id===activeId,persistence:target.pc,birth:born,collapse}});centersRef.current=centers;
 const field=ctx.createRadialGradient(cx,cy,0,cx,cy,Math.min(w,h)*.5*z);field.addColorStop(0,"rgba(244,114,182,.13)");field.addColorStop(.35,"rgba(217,70,239,.06)");field.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=field;ctx.fillRect(0,0,w,h);ctx.beginPath();ctx.arc(cx,cy,5,0,Math.PI*2);ctx.fillStyle="rgba(254,249,195,.96)";ctx.shadowBlur=22;ctx.shadowColor="rgba(253,224,71,.75)";ctx.fill();ctx.shadowBlur=0;
 for(const e of edges){const a=centers.find(c=>c.id===e.from),b=centers.find(c=>c.id===e.to);if(!a||!b)continue;ctx.globalAlpha=Math.min(a.birth,b.birth)*(1-Math.max(a.collapse,b.collapse)*.8);ctx.beginPath();ctx.moveTo(a.x,a.y);const mx=(a.x+b.x)/2+(b.y-a.y)*.06,my=(a.y+b.y)/2-(b.x-a.x)*.06;ctx.quadraticCurveTo(mx,my,b.x,b.y);ctx.setLineDash(e.relation==="depends_on"?[3,8]:e.relation==="closes"?[1,10]:[]);ctx.strokeStyle=e.relation==="opens"?"rgba(34,211,238,.28)":e.relation==="contradicts"?"rgba(251,146,60,.24)":e.relation==="closes"?"rgba(244,63,94,.24)":"rgba(217,70,239,.14)";ctx.stroke();ctx.setLineDash([])}ctx.globalAlpha=1;
 for(const c of centers){const hover=c.id===hoverRef.current,scale=(.18+.82*c.birth)*(1-.82*c.collapse),base=c.selected?15:hover?11:c.persistence==="observed_fragile"?8:6.5;for(let i=0;i<44;i++){const a=(i/44)*Math.PI*2+now*.00015*(c.persistence==="observed_fragile"?2.2:.7),spread=(c.persistence==="observed_fragile"?34:c.persistence==="observed_persistent"?17:24)*scale;const x=c.x+Math.cos(a*1.07)*spread*(.45+((i*17)%23)/23),y=c.y+Math.sin(a)*spread*(.45+((i*11)%19)/19);ctx.beginPath();ctx.arc(x,y,hover?1.5:.85,0,Math.PI*2);ctx.fillStyle=c.selected?"rgba(244,114,182,.76)":c.persistence==="observed_persistent"?"rgba(103,232,249,.48)":c.persistence==="observed_fragile"?"rgba(251,146,60,.38)":c.closed?"rgba(244,63,94,.12)":"rgba(217,70,239,.4)";ctx.fill()}ctx.beginPath();ctx.arc(c.x,c.y,Math.max(.8,base*scale),0,Math.PI*2);ctx.strokeStyle=c.selected?"rgba(244,114,182,.98)":hover?"rgba(255,255,255,.9)":stroke(c.persistence);ctx.lineWidth=c.selected||hover?1.8:1;ctx.shadowBlur=c.selected?24:hover?18:8;ctx.shadowColor=ctx.strokeStyle;ctx.stroke();ctx.shadowBlur=0;if(c.birth<1){ctx.beginPath();ctx.arc(c.x,c.y,base*(1+c.birth*2.2),0,Math.PI*2);ctx.strokeStyle=`rgba(244,114,182,${(1-c.birth)*.55})`;ctx.stroke()}}
 raf=requestAnimationFrame(draw)};draw();return()=>{cancelAnimationFrame(raf);ro.disconnect()}},[graph,persistence,activeId]);
 const nearest=(x:number,y:number)=>{let best:Center|undefined,d=Infinity;for(const c of centersRef.current){const nd=Math.hypot(x-c.x,y-c.y);if(nd<d){d=nd;best=c}}return best&&d<72?best:undefined};
 const move=(e:ReactMouseEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(dragRef.current){panRef.current={x:dragRef.current.px+x-dragRef.current.x,y:dragRef.current.py+y-dragRef.current.y};return}const id=nearest(x,y)?.id;hoverRef.current=id;if(id!==hoveredId)setHoveredId(id)};
 const down=(e:ReactMouseEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();dragRef.current={x:e.clientX-r.left,y:e.clientY-r.top,px:panRef.current.x,py:panRef.current.y}};const up=()=>{dragRef.current=null};
 const click=(e:ReactMouseEvent<HTMLCanvasElement>)=>{if(!onSelect)return;const r=e.currentTarget.getBoundingClientRect(),hit=nearest(e.clientX-r.left,e.clientY-r.top);if(hit)onSelect(hit.id)};
 const wheel=(e:ReactWheelEvent<HTMLCanvasElement>)=>{e.preventDefault();zoomRef.current=clamp(zoomRef.current*(e.deltaY>0?.92:1.08),.65,2.4)};const resetView=()=>{zoomRef.current=1;panRef.current={x:0,y:0}};
 return <div className="relative min-h-[68vh] overflow-hidden rounded-[36px] border border-fuchsia-300/[.10] bg-[#010104]"><canvas ref={canvasRef} onMouseMove={move} onMouseLeave={()=>{hoverRef.current=undefined;setHoveredId(undefined);up()}} onMouseDown={down} onMouseUp={up} onClick={click} onWheel={wheel} className="absolute inset-0 h-full w-full cursor-grab active:cursor-grabbing"/><div className="pointer-events-none absolute left-6 top-6"><p className="text-[9px] tracking-[.30em] text-fuchsia-100/45">MPE · LIVING POSSIBILITY SPACE</p><p className="mt-2 max-w-md text-xs leading-5 text-white/30">Las ramas nuevas emergen desde su genealogía. Las cerradas se contraen progresivamente. Transición visual ≠ evidencia.</p></div>{hovered?<div className="pointer-events-none absolute left-1/2 top-1/2 max-w-xs -translate-x-1/2 translate-y-8 rounded-2xl border border-white/10 bg-black/70 px-4 py-3 backdrop-blur"><p className="text-[8px] text-fuchsia-100/45">{hovered.epistemicStatus.toUpperCase()} · {hovered.lifecycleStage.toUpperCase()}</p><p className="mt-1 text-xs text-white/75">{hovered.title}</p></div>:null}<button onClick={resetView} className="absolute bottom-6 right-6 rounded-full border border-white/10 bg-black/35 px-3 py-2 text-[8px] text-white/35">RESET VIEW</button><div className="pointer-events-none absolute bottom-6 left-6 text-[8px] tracking-[.13em] text-white/25">BIRTH · LINEAGE · PERSISTENCE · COLLAPSE · NON-PROBABILISTIC</div></div>}
