import type { Metadata } from "next";
import { Anchor, Bath, Bluetooth, Droplets, Flame, MapPin, Music2, Ship, Users, Waves } from "lucide-react";
import "./bzlanchas.css";

export const metadata: Metadata={title:"BZ Lanchas | Passeio Privativo em Búzios",description:"Passeio privativo em Búzios em lancha cabinada de 27,5 pés para até 10 pessoas."};
const whatsapp="https://wa.me/5522997362297?text=Ol%C3%A1%21%20Quero%20consultar%20a%20disponibilidade%20da%20BZ%20Lanchas.";
const roteiro=["Armação","Praia do Canto","Amores","Tartaruguinha","Tartaruga","Ossos","Azeda","Azedinha","João Fernandes","João Fernandinho"];
const features=[["Quarto","na cabine",Anchor],["Banheiro","com vaso elétrico",Bath],["Som","Bluetooth",Music2],["Pia","com água doce",Droplets],["Ducha","com água doce",Waves],["Churrasqueira","a bordo",Flame]] as const;
export default function Page(){return <main className="bz">
<header className="nav"><a className="logo imageLogo" href="#inicio"><img src="/logolancha.jpeg" alt="BZ Lanchas" /></a><nav><a href="#inicio">Início</a><a href="#lancha">Lanchas</a><a href="#roteiro">Roteiros</a><a href="#galeria">Galeria</a><a href="#contato">Contato</a></nav><a className="outline" href={whatsapp}>◉ FALE NO WHATSAPP</a></header>
<section className="hero" id="inicio"><div className="heroPhoto photoHero"/><div className="shade"/><div className="heroCopy"><p className="eyebrow">EXPERIÊNCIAS EXCLUSIVAS EM BÚZIOS</p><h1>BÚZIOS<br/>VISTO DE<br/><em>OUTRO ÂNGULO.</em></h1><p>Passeios privativos de lancha para viver o mar com liberdade, conforto e momentos inesquecíveis.</p><a className="gold" href={whatsapp}>◉ FALE NO WHATSAPP <b>→</b></a></div><div className="script">Búzios<br/><small>é mais vida aqui.</small></div></section>
<section className="quick"><div><Ship/><b>27,5 PÉS</b><span>LANCHA CABINADA</span></div><div><Users/><b>ATÉ 10 PESSOAS</b><span>PASSEIO PRIVATIVO</span></div><div><Anchor/><b>CONFORTO</b><span>PARA CURTIR O DIA</span></div><div><MapPin/><b>ROTEIRO PELOS</b><span>MELHORES PONTOS</span></div></section>
<section className="catalog" id="lancha">
  <div className="catalogHead"><div><p className="eyebrow">ESCOLHA SUA EXPERIÊNCIA</p><h2>NOSSAS EMBARCAÇÕES</h2><p>Uma seleção preparada para viver Búzios pelo mar. Hoje, nossa 27,5 pés está disponível; novas embarcações serão apresentadas em breve.</p></div><div className="catalogTools"><span>1 EMBARCAÇÃO DISPONÍVEL</span><a href={whatsapp}>CONSULTAR DISPONIBILIDADE</a></div></div>
  <div className="fleet">
    <article className="fleetCard fleetReal"><div className="fleetPhoto"><span className="available">DISPONÍVEL</span><span className="fleetIndex">01</span></div><div className="fleetBody"><p className="eyebrow">PASSEIO PRIVATIVO</p><h3>LANCHA CABINADA <em>27,5 PÉS</em></h3><div className="fleetFacts"><span><Users/>ATÉ 10 PESSOAS</span><span><Bath/>BANHEIRO</span><span><Flame/>CHURRASQUEIRA</span></div><p>Conforto, privacidade e estrutura completa para descobrir os melhores pontos de Búzios.</p><div className="fleetActions"><a className="gold" href="#detalhes">VER DETALHES →</a><a className="fleetWhatsapp" href={whatsapp}>◉ RESERVAS</a></div></div></article>
    <article className="fleetCard fleetSoon"><div className="soonVisual"><Ship/><span>02</span></div><div className="fleetBody"><p className="eyebrow">NOVA EMBARCAÇÃO</p><h3>EM BREVE</h3><p>Este espaço está preparado para receber a próxima lancha da frota BZ.</p><span className="soonLabel">FOTOS E DETALHES EM BREVE</span></div></article>
    <article className="fleetCard fleetSoon"><div className="soonVisual"><Waves/><span>03</span></div><div className="fleetBody"><p className="eyebrow">NOVA EMBARCAÇÃO</p><h3>EM BREVE</h3><p>Novas experiências serão adicionadas ao catálogo conforme a frota crescer.</p><span className="soonLabel">FOTOS E DETALHES EM BREVE</span></div></article>
  </div>
</section>
<section className="boat" id="detalhes"><div className="boatCopy"><p className="eyebrow">CONHEÇA NOSSA LANCHA</p><h2>27,5 PÉS<br/>CABINADA</h2><h3>CONFORTO EM TODOS OS DETALHES</h3><p>Uma embarcação completa, ideal para quem busca privacidade, conforto e a melhor experiência em Búzios.</p><a className="gold" href={whatsapp}>◉ FALE NO WHATSAPP →</a></div><div className="mosaic"><div className="ph photo cockpit"><span>ÁREA EXTERNA</span></div><div className="ph photo cabin"><span>CABINE</span></div><div className="ph photo bath"><span>BANHEIRO</span></div><div className="ph photo boatpic"><span>27,5 PÉS</span></div></div></section>
<section className="amenities"><h3>ESTRUTURA E COMODIDADES</h3><div>{features.map(([a,b,I])=><article key={a}><I/><b>{a}</b><span>{b}</span></article>)}</div></section>
<section className="route" id="roteiro"><div className="routeVisual photoRoute"><p className="eyebrow">CENÁRIOS INCRÍVEIS EM UM SÓ PASSEIO</p><h2>ROTEIRO<br/>POR BÚZIOS</h2><p>Descubra algumas das praias mais desejadas da península pelo melhor ponto de vista: o mar.</p></div><div className="routeList">{roteiro.map((r,i)=><div key={r}><i>{i+1}</i><span>{r}</span></div>)}</div></section>
<section className="gallery" id="galeria"><div className="sectionHead"><div><p className="eyebrow">MOMENTOS QUE FICAM</p><h2>GALERIA DE EXPERIÊNCIAS</h2></div></div><div className="galleryGrid"><div className="ph photo bow"/><div className="ph photo cockpit"/><div className="ph photo sea"/><div className="ph photo sunset"/></div></section>
<section className="included"><p className="eyebrow">INCLUSO NO PASSEIO</p><div><span>❄<b>Gelo em escamas</b></span><span>♨<b>Carvão</b></span><span>♢<b>Água mineral</b></span></div></section>
<section className="final photoFinal" id="contato"><div><h2>PRONTO PARA VIVER<br/>ESSA EXPERIÊNCIA?</h2><p>Entre em contato agora e consulte a disponibilidade.</p><a className="gold" href={whatsapp}>◉ FALE NO WHATSAPP →</a></div><div className="script">Mais que um passeio,<br/><small>uma experiência.</small></div></section>
<footer><a className="logo imageLogo footerLogo" href="#inicio"><img src="/logolancha.jpeg" alt="BZ Lanchas" /></a><p className="script">Búzios é mais vida aqui.</p><p>@Bzlanchas &nbsp; • &nbsp; (22) 99736-2297</p></footer>
</main>}