"use client";
import {useMemo,useState} from "react";
import MpeInterfaceFrame from "../MpeInterfaceFrame";
import {buildNarrativeState,generateNarrativePossibilities,transitionNarrativeState,LITERARY_BOUNDARIES,type NarrativePossibility} from "./literary-engine";
import {ENTITY_BIBLE_MANIFEST} from "./knowledge-fabric";
import {reconstructNarrativeContext} from "./context-reconstructor";
import {analyzeWithMcos,mcosBridgeConfigured,MCOS_BRIDGE_BOUNDARY,type McosBridgeState,type McosLiteraryResponse} from "./mcos-bridge";

const sample="Una hoja quedó sobre la mesa. Felipe volvió a mirarla antes de tocarla. La pregunta no era qué significaba el dibujo, sino por qué seguía apareciendo.";

export default function MpeLiterarySurface(){
 const [text,setText]=useState(""); const [started,setStarted]=useState(false); const [selected,setSelected]=useState<NarrativePossibility|null>(null);
 const [mcosState,setMcosState]=useState<McosBridgeState>(mcosBridgeConfigured()?"UNREACHABLE":"UNCONFIGURED"); const [mcos,setMcos]=useState<McosLiteraryResponse|null>(null);
 const state=useMemo(()=>buildNarrativeState(text),[text]);
 const context=useMemo(()=>reconstructNarrativeContext(state),[state]);
 const possibilities=useMemo(()=>started?generateNarrativePossibilities(state,context):[],[started,state,context]);
 const nextState=selected?transitionNarrativeState(state,selected):null;
 const change=(v:string)=>{setText(v);setStarted(false);setSelected(null);setMcos(null);setMcosState(mcosBridgeConfigured()?"UNREACHABLE":"UNCONFIGURED")};
 const awaken=async()=>{if(!text.trim())return;setStarted(true);setSelected(null);setMcos(null);if(!mcosBridgeConfigured()){setMcosState("UNCONFIGURED");return}setMcosState("CONNECTING");try{const result=await analyzeWithMcos(text,context.domains);setMcos(result);setMcosState("AVAILABLE")}catch{setMcosState("UNREACHABLE")}};
 return <MpeInterfaceFrame active="LITERATURE"><main className="min-h-screen bg-[#010104] px-3 py-4 sm:px-5">
  <section className="grid gap-4 xl:grid-cols-[300px_minmax(0,1fr)_330px]">
   <aside className="rounded-[30px] border border-violet-300/[.10] bg-[#07030b]/75 p-5 backdrop-blur-xl">
    <p className="text-[9px] tracking-[.26em] text-violet-100/48">MPE · LITERARY ORGAN</p><h1 className="mt-5 text-3xl font-light leading-tight text-white/88">La obra como estado vivo.</h1>
    <p className="mt-4 text-xs leading-6 text-white/35">Observa el estado narrativo, reconstruye contexto desde fuentes declaradas y abre posibilidades que deben transformar algo.</p>
    <textarea value={text} onChange={e=>change(e.target.value)} placeholder="Pegá una escena, capítulo o estado narrativo..." className="mt-6 min-h-56 w-full resize-none rounded-2xl border border-white/[.07] bg-black/25 p-4 text-xs leading-6 text-white/70 outline-none placeholder:text-white/20"/>
    <div className="mt-3 flex gap-2"><button onClick={()=>change(sample)} className="rounded-full border border-white/[.07] px-3 py-2 text-[9px] text-white/35">EJEMPLO</button><button disabled={!text.trim()||mcosState==="CONNECTING"} onClick={awaken} className="flex-1 rounded-full border border-violet-300/25 bg-violet-300/[.08] px-4 py-2 text-[9px] tracking-[.15em] text-violet-50 disabled:opacity-25">{mcosState==="CONNECTING"?"MCOS...":"ABRIR ESTADO"}</button></div>
    <div className="mt-6 border-t border-white/[.05] pt-5"><div className="flex items-center justify-between"><p className="text-[9px] tracking-[.15em] text-white/30">KNOWLEDGE FABRIC</p><span className="rounded-full border border-cyan-300/10 px-2 py-1 text-[7px] tracking-[.12em] text-cyan-100/40">{ENTITY_BIBLE_MANIFEST.status}</span></div><p className="mt-3 text-[10px] leading-5 text-white/38">ENTITY BIBLE · {ENTITY_BIBLE_MANIFEST.totalDocuments} docs · {ENTITY_BIBLE_MANIFEST.totalDomains} domains</p><p className="mt-2 text-[8px] leading-4 text-amber-100/35">El Context Reconstructor usa una proyección source-derived con trazabilidad. No afirma todavía lectura semántica completa de los 222 documentos.</p>{started?<div className="mt-4 flex flex-wrap gap-2">{context.domains.map(domain=><span key={domain.id} className="rounded-full border border-violet-300/10 bg-violet-300/[.025] px-2 py-1 text-[8px] text-violet-100/42">{domain.id} · {domain.documentCount}</span>)}</div>:null}</div>
    <div className="mt-5 rounded-2xl border border-white/[.05] bg-black/20 p-4"><div className="flex items-center justify-between"><p className="text-[9px] tracking-[.15em] text-white/30">MCOS ADAPTER</p><span className="text-[8px] text-white/35">{mcosState}</span></div><p className="mt-2 text-[8px] leading-4 text-white/24">Backend remoto sólo cuenta como activo cuando responde de forma observable.</p></div>
   </aside>
   <section className="relative min-h-[680px] overflow-hidden rounded-[34px] border border-fuchsia-300/[.08] bg-[radial-gradient(circle_at_50%_42%,rgba(139,92,246,.14),rgba(15,5,25,.65)_35%,rgba(1,1,4,.98)_72%)] p-6">
    <div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.025)_1px,transparent_1px)] [background-size:42px_42px]"/>
    {!started?<div className="relative grid h-full min-h-[620px] place-items-center text-center"><div><p className="text-[9px] tracking-[.35em] text-fuchsia-100/25">NARRATIVE STATE · IDLE</p><p className="mt-5 text-4xl font-extralight text-white/70">S(t) todavía no fue abierto.</p><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-white/25">Una fuente narrativa activa el espacio de transformación.</p></div></div>:<div className="relative">
     <div className="mx-auto max-w-2xl text-center"><p className="text-[9px] tracking-[.3em] text-cyan-100/35">S(t) · OBSERVED SOURCE</p><h2 className="mt-4 text-3xl font-light text-white/80">{state.hiddenQuestion}</h2><div className="mt-5 flex flex-wrap justify-center gap-2">{state.objects.map(x=><span key={x} className="rounded-full border border-cyan-300/10 px-3 py-1 text-[9px] text-cyan-100/45">OBJECT · {x}</span>)}{state.themes.map(x=><span key={x} className="rounded-full border border-fuchsia-300/10 px-3 py-1 text-[9px] text-fuchsia-100/45">THEME · {x}</span>)}</div></div>
     <div className="mx-auto mt-10 max-w-4xl rounded-[24px] border border-cyan-300/[.07] bg-cyan-300/[.02] p-4"><div className="flex items-center justify-between"><p className="text-[9px] tracking-[.16em] text-cyan-100/45">ACTIVE CONTEXT · {context.status}</p><span className="text-[8px] text-white/25">{context.sourceCount} source traces</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{context.principles.map(principle=><div key={principle.id} className="rounded-2xl border border-white/[.05] bg-black/20 p-3"><p className="text-[8px] tracking-[.12em] text-cyan-100/35">{principle.id}</p><p className="mt-2 text-[10px] leading-5 text-white/38">{principle.text}</p></div>)}</div></div>
     {mcos?<div className="mx-auto mt-4 max-w-4xl rounded-[24px] border border-emerald-300/[.09] bg-emerald-300/[.025] p-4"><div className="flex items-center justify-between"><p className="text-[9px] tracking-[.16em] text-emerald-100/50">MCOS · {mcos.adapter.mode}</p><span className="text-[8px] text-emerald-100/35">v{mcos.adapter.version}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><Metric label="BODY RULE" value={mcos.analysis.diagnostics.body_rule_score}/><Metric label="SHOW / TELL" value={mcos.analysis.diagnostics.show_vs_tell_score}/><Metric label="QUESTION" value={mcos.analysis.diagnostics.hidden_question_presence}/></div><p className="mt-3 text-[9px] leading-5 text-white/30">Blueprint ready: {String(mcos.readiness.ready_for_scene_dna)} · Full MCOS: {String(mcos.readiness.ready_for_full_mcos)}</p></div>:null}
     <div className="mx-auto mt-6 grid max-w-4xl gap-3 sm:grid-cols-2">{possibilities.map((p,i)=><button key={p.id} onClick={()=>setSelected(p)} className={`min-h-44 rounded-[26px] border p-5 text-left transition ${selected?.id===p.id?"border-violet-300/35 bg-violet-300/[.09]":"border-white/[.07] bg-black/25 hover:border-violet-300/20"}`}><p className="text-[8px] tracking-[.2em] text-white/25">P{String(i+1).padStart(2,"0")} · {p.status.toUpperCase()}</p><h3 className="mt-3 text-lg font-light text-white/75">{p.title}</h3><p className="mt-3 text-[11px] leading-5 text-white/38">{p.transformation}</p><p className="mt-4 text-[8px] text-violet-100/35">PROPOSED · NOT CANON · {p.contextSources.length} SOURCE LINKS</p></button>)}</div>
     <div className="mx-auto mt-8 max-w-3xl rounded-2xl border border-white/[.05] bg-black/25 p-4 text-center text-[9px] leading-5 text-white/28">S(t) → CONTEXT RECONSTRUCTOR → MCOS ADAPTER → POSSIBILITY SPACE → CONTINUITY PRESSURE → SCENE → CONSEQUENCE → MEMORY → S(t+1)</div>
    </div>}
   </section>
   <aside className="rounded-[30px] border border-cyan-300/[.07] bg-[#03090d]/70 p-5 backdrop-blur-xl"><p className="text-[9px] tracking-[.24em] text-cyan-200/42">MAX · NARRATIVE OBSERVER</p>{started?<><div className="mt-5 space-y-4"><Panel title="STATE" values={[`Objects · ${state.objects.join(" · ")||"unobserved"}`,`Locations · ${state.locations.join(" · ")||"unobserved"}`,`Body · ${state.bodySignals.join(" · ")||"unobserved"}`]}/><Panel title="ACTIVE KNOWLEDGE" values={[`${context.domains.length} domains · ${context.sourceCount} source traces`,...context.principles.map(principle=>`${principle.id} · ${principle.sources[0]}`)]}/>{mcos?<Panel title="MCOS PROVENANCE" values={mcos.provenance.map(p=>`${p.status} · ${p.source}`)}/>:null}<Panel title="OPEN THREADS" values={state.openThreads}/><Panel title="PROVENANCE" values={state.provenance.map(p=>`${p.status} · ${p.source}`)}/></div>{selected&&nextState?<div className="mt-5 rounded-2xl border border-violet-300/12 bg-violet-300/[.03] p-4"><p className="text-[9px] tracking-[.15em] text-violet-100/50">PROPOSED TRANSITION · S(t+1)</p><p className="mt-3 text-xs leading-6 text-white/48">{selected.transformation}</p><p className="mt-3 text-[9px] leading-5 text-white/28">Changes: {selected.changes.join(" · ")}</p><p className="mt-3 text-[9px] leading-5 text-white/25">Context: {selected.contextSources.join(" · ")||"no source projection"}</p><p className="mt-3 text-[8px] text-amber-100/40">No modifica canon hasta aprobación/observación.</p></div>:null}</>:<p className="mt-8 text-sm leading-7 text-white/25">El observador se activa cuando existe una fuente narrativa.</p>}<div className="mt-7 border-t border-white/[.05] pt-5"><p className="text-[9px] tracking-[.14em] text-white/28">BOUNDARIES</p>{[...LITERARY_BOUNDARIES,ENTITY_BIBLE_MANIFEST.boundary,...context.boundaries,MCOS_BRIDGE_BOUNDARY,...(mcos?.boundaries??[])].map(x=><p key={x} className="mt-2 break-words text-[8px] leading-4 text-white/20">{x}</p>)}</div></aside>
  </section>
 </main></MpeInterfaceFrame>
}
function Panel({title,values}:{title:string;values:string[]}){return <div className="rounded-2xl border border-white/[.05] bg-black/20 p-4"><p className="text-[9px] tracking-[.15em] text-cyan-100/38">{title}</p>{values.map(v=><p key={v} className="mt-2 text-[10px] leading-5 text-white/38">{v}</p>)}</div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/[.05] bg-black/20 p-3"><p className="text-[8px] tracking-[.12em] text-white/28">{label}</p><p className="mt-2 text-xl font-light text-white/65">{value}</p></div>}
